default_url_options:
  protocol: 'https'
  host: 'infinite-coast-76610-6cf707f3e38e.herokuapp.com'

smtp_settings:
  user_name: 'apikey'
  password: 'SENDGRID_API_KEY'  # これがENVから読み込まれる
  domain: 'infinite-coast-76610-6cf707f3e38e.herokuapp.com'
  address: 'smtp.sendgrid.net'
  port: 587
  authentication: 'plain'
  enable_starttls_auto: true