default_url_options:
  protocol: 'https'
  host: 'infinite-coast-76610.herokuapp.com'

smtp_settings:
  user_name: 'apikey'  # 文字通り'apikey'と記述します
  password: <%= ENV['SENDGRID_API_KEY'] %>
  domain: 'infinite-coast-76610.herokuapp.com'
  address: 'smtp.sendgrid.net'
  port: 587
  authentication: 'plain'
  enable_starttls_auto: true
